-- 设备告警表
CREATE TABLE IF NOT EXISTS `qs_device_alarm` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `device_id` bigint DEFAULT NULL COMMENT '设备ID',
  `device_code` varchar(64) DEFAULT NULL COMMENT '设备编号',
  `device_name` varchar(128) DEFAULT NULL COMMENT '设备名称',
  `alarm_type` varchar(32) DEFAULT NULL COMMENT '告警类型（motion-动态检测，video_loss-视频丢失，cover-视频遮挡，cross_line-越界检测，enter_area-区域入侵，leave_area-区域离开，object_remove-物品移除，object_leave-物品遗留，face_detection-人脸检测，other-其他）',
  `alarm_level` varchar(32) DEFAULT NULL COMMENT '告警级别（low-低，medium-中，high-高，critical-紧急）',
  `sdk_type` varchar(32) DEFAULT NULL COMMENT 'SDK类型（hik-海康，hik_isup-海康ISUP，dahua-大华，uniview-宇视，tiandy-天地伟业，gb28181-国标28181，other-其他）',
  `channel` int DEFAULT NULL COMMENT '通道号',
  `alarm_time` datetime DEFAULT NULL COMMENT '告警时间',
  `alarm_content` text COMMENT '告警内容',
  `image_url` varchar(512) DEFAULT NULL COMMENT '告警图片URL',
  `handled` tinyint(1) DEFAULT 0 COMMENT '是否已处理（0-否，1-是）',
  `handler` varchar(64) DEFAULT NULL COMMENT '处理人',
  `handle_time` datetime DEFAULT NULL COMMENT '处理时间',
  `create_by` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_device_id` (`device_id`),
  KEY `idx_device_code` (`device_code`),
  KEY `idx_alarm_type` (`alarm_type`),
  KEY `idx_alarm_level` (`alarm_level`),
  KEY `idx_sdk_type` (`sdk_type`),
  KEY `idx_alarm_time` (`alarm_time`),
  KEY `idx_handled` (`handled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设备告警表';
